version: '3'

services:
  db: # Service name
    image: postgres:14.3
    restart: always
    ports: # Port mapping
      - "5432:5432"
    environment: # Environment variables
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb # Name of the container
    volumes: # Persist data
      - ./postgres:/var/lib/postgresql/data # Persist data